version: '3.5'
name: 'geoquizz'
networks:
  geoquizz.net:
    driver: bridge

services:

  #############################
  ### Gateway               ###
  #############################

  gateway:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '35200:80'
    volumes:
      - ../api/gateway:/var/www/
      - ../api/gateway/public:/var/www/html
    working_dir: /var/www
    networks:
      - geoquizz.net

  #############################
  ### WS GeoQuizz           ###
  #############################

  ws_geoquizz:
    image: 'node:alpine'
    ports:
      - '35201:3000'
    env_file: ./ws.env
    command: sh -c "npm i && npm run watch"
    volumes:
      - ../api/ws_geoquizz:/app
    working_dir: /app
    networks:
      - geoquizz.net

  #############################
  ### Adminer              ###
  #############################

  adminer:
    image: adminer
    ports:
      - '35202:8080'
    networks:
      - geoquizz.net

  ########################################
  # Broker de message RabbitMQ #
  ########################################

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '35203:15672' # interface web de gestion et administration
      - '35204:5672'  # api pour publier et consommer des messages
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 8s
      timeout: 30s
      retries: 3
    networks:
      - geoquizz.net
    volumes:
      - ../api/rabbitmq:/var/lib/rabbitmq
    env_file: ./rab.env

  #############################
  ### AUTH                 ###
  #############################

  auth_php:
    image: 'canals/php:8.2'
    env_file: ./auth.env
    ports:
      - '35205:80'
    volumes:
      - ../api/auth:/var/www/
      - ../api/auth/public:/var/www/html
      - ./auth.env:/config/.env
    working_dir: /var/www
    networks:
      - geoquizz.net

  auth_db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./auth.env
    ports:
      - '35207:3306'
    networks:
      - geoquizz.net

  #############################
  ### Service Geoquizz      ###
  #############################

  service_geoquizz_php:
    image: 'canals/php:8.2'
    env_file: ./service.env
    ports:
      - '35206:80'
    volumes:
      - ../api/service_geoquizz:/var/www
      - ../api/service_geoquizz/public:/var/www/html
    working_dir: /var/www
    networks:
      - geoquizz.net

  service_geoquizz_db:
    image: 'postgres:latest'
    env_file: ./service.env
    ports:
      - '35208:5432'
    networks:
      - geoquizz.net

  #############################
  ### Web with Apache ###
  #############################

  web:
    image: httpd:latest
    ports:
      - "35209:80"
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache-iutnc.univ-lorraine.fr:3128
    volumes:
      - ../web/dist:/usr/local/apache2/htdocs/geoquizz
    networks:
      - geoquizz.net

  #############################
  ### DIRECTUS ###
  #############################

  directus_db:
    image: postgis/postgis:13-master
    networks:
      - geoquizz.net
    env_file:
      - directus_db.env
    ports:
      - "35211:5432"
    volumes:
      - ../api/directus/data/database:/var/lib/postgresql/data

  cache:
      image: redis:6
      networks:
        - geoquizz.net
      ports:
        - '35212:8055'


  directus:
      image: directus/directus:10.8.3
      networks:
        - geoquizz.net
      env_file:
        - directus.env
      ports:
        - '35210:8055'
      volumes:
        - ../api/directus/uploads:/directus/uploads
        # If you want to load extensions from the host
        # - ./extensions:/directus/extensions
      depends_on:
        - cache
        - directus_db